'use client';
import { useMemo, useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence, MotionConfig, useReducedMotion } from 'motion/react';
import { ArrowUpRight, ArrowRight, DownloadSimple, MagnifyingGlass, SquaresFour, List, X, Check, Cube, ShieldCheck, FileCsv, GithubLogo } from '@phosphor-icons/react';
import { toCSV } from '../lib/csv.mjs';
import sample from '../lib/demo.json';
const ORDER=['Contraband','Extraordinary','Covert','Classified','Restricted','Mil-Spec Grade','Mil-Spec','Exotic','Remarkable','Superior','Distinguished','Master','Exceptional','Industrial Grade','High Grade','Consumer Grade','Base Grade'];
const rank=r=>ORDER.indexOf(r)<0?99:ORDER.indexOf(r);
const fmt=n=>n.toLocaleString('en-US');
function download(name,rows){const url=URL.createObjectURL(new Blob([toCSV(rows)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function HomePage(){
 const [profile,setProfile]=useState(''),[status,setStatus]=useState('idle'),[error,setError]=useState(null),[data,setData]=useState(null),[query,setQuery]=useState(''),[rarity,setRarity]=useState(''),[tradable,setTradable]=useState(false),[sort,setSort]=useState('inventory'),[grouped,setGrouped]=useState(true),[view,setView]=useState('grid'),[selected,setSelected]=useState(null),[exported,setExported]=useState(false);
 const reduced=useReducedMotion(),inventory=useRef(null),request=useRef(null),dialog=useRef(null);
 useEffect(()=>()=>request.current?.abort(),[]);
 useEffect(()=>{if(selected)dialog.current?.showModal();},[selected]);
 function reset(body){setData(body);setQuery('');setRarity('');setTradable(false);setSort('inventory');setStatus('done');setExported(false);}
 function demo(){request.current?.abort();setError(null);reset(sample);}
 async function load(e){e.preventDefault();if(!profile.trim()){setError({message:'Paste a Steam profile link or ID to get started.'});return;}request.current?.abort();const controller=new AbortController();request.current=controller;setStatus('loading');setError(null);try{const r=await fetch('/api/get-inventory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile}),signal:controller.signal});const b=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(b.message||'Could not load this inventory. Please try again.'),{code:b.code});reset(b);}catch(e){if(e.name==='AbortError')return;setError({message:e.message,code:e.code});setStatus(data?'done':'idle');}}
 const stats=useMemo(()=>data?{total:data.items.reduce((s,i)=>s+i.amount,0),unique:new Set(data.items.map(i=>i.name)).size,tradable:data.items.filter(i=>i.tradable).reduce((s,i)=>s+i.amount,0),rarities:[...new Set(data.items.map(i=>i.rarity).filter(Boolean))].sort((a,b)=>rank(a)-rank(b))}:null,[data]);
 const filtered=useMemo(()=>{if(!data)return[];const q=query.toLowerCase().trim();let rows=data.items.filter(i=>(!q||i.name.toLowerCase().includes(q)||(i.collection||'').toLowerCase().includes(q))&&(!rarity||rarity===i.rarity)&&(!tradable||i.tradable));if(sort==='rarity')rows=[...rows].sort((a,b)=>rank(a.rarity)-rank(b.rarity));if(sort==='name')rows=[...rows].sort((a,b)=>a.name.localeCompare(b.name));return rows;},[data,query,rarity,tradable,sort]);
 const shown=useMemo(()=>{if(!grouped)return filtered;const m=new Map();for(const i of filtered){const k=`${i.name}|${i.tradable}|${i.tradeHold}`;if(m.has(k))m.get(k).amount+=i.amount;else m.set(k,{...i});}return[...m.values()];},[filtered,grouped]);
 function exportRows(rows){download(`cs2_inventory_${data.steamId}${rows!==data.items?'_filtered':''}.csv`,rows);setExported(true);}
 return <MotionConfig reducedMotion="user"><div className="app-shell">
 <header className="topbar"><a className="brand" href="#top"><span className="brand-mark"><Cube size={23} weight="bold"/></span><span>CS2 <strong>Inventory</strong></span></a><a className="source-link" href="https://github.com/harsh-github007/cs2-inventory-exporter" target="_blank" rel="noreferrer"><GithubLogo size={19}/>Source<ArrowUpRight size={14}/></a></header>
 <main id="top">
 <section className={`intro ${data?'intro-compact':''}`}>
 <div className="intro-copy"><motion.h1 layout>{data?<>Browse and export<br/><span>your CS2 inventory.</span></>:<>Export a public<br/><span>CS2 inventory to CSV.</span></>}</motion.h1><p>View items from a public Steam profile, filter the inventory, and download a CSV spreadsheet.</p>
 <form onSubmit={load} className="profile-form"><label htmlFor="profile">Public Steam profile</label><div className="profile-control"><input id="profile" value={profile} onChange={e=>setProfile(e.target.value)} placeholder="steamcommunity.com/id/your-name" autoComplete="off" spellCheck="false"/><button className="primary" disabled={status==='loading'}>{status==='loading'?'Reading Steam…':'Open inventory'}<ArrowRight size={19}/></button></div><p className="input-help">Profile URL, SteamID64 or custom profile name. No sign-in needed.</p></form>
 <div className="sample-line"><button className="text-button" onClick={demo}>Try the sample collection<ArrowUpRight size={16}/></button><span>See it before you connect.</span></div>
 <AnimatePresence>{error&&<motion.div role="alert" className="error-message" initial={{opacity:0,y:reduced?0:6}} animate={{opacity:1,y:0}} exit={{opacity:0}}><b>{error.message}</b>{error.code==='private'&&<p>Steam → Edit Profile → Privacy Settings: set your profile and inventory to Public.</p>}{error.code==='rate_limited'&&<p>Steam is limiting requests. Wait a few minutes, then try again.</p>}</motion.div>}</AnimatePresence>
 </div>
 {!data&&<div className="collection-scene" aria-label="Illustrative sample collection"><div className="scene-caption"><span>THE LOADOUT</span><span>Sample collection</span></div><motion.div className="showcase-item main-item" initial={{opacity:0,y:reduced?0:20,rotate:-3}} animate={{opacity:1,y:0,rotate:-3}} transition={{duration:.5,ease:[.16,1,.3,1]}}><span className="item-edition">CLASSIFIED · RIFLE</span><img src="/items/item-0.png" alt="AK-47 Redline"/><div><b>AK-47</b><span>Redline</span></div><i className="rarity-stripe"/></motion.div><motion.div className="showcase-item second-item" initial={{opacity:0,y:reduced?0:30,rotate:5}} animate={{opacity:1,y:0,rotate:5}} transition={{duration:.5,delay:.08,ease:[.16,1,.3,1]}}><img src="/items/item-1.png" alt="AWP Asiimov"/><div><b>AWP</b><span>Asiimov</span></div></motion.div><div className="export-ticket"><FileCsv size={25}/><div><b>Your inventory.csv</b><span>Names · wear · rarity · trade status</span></div><Check size={20}/></div></div>}
 </section>
 <AnimatePresence mode="wait">{status==='loading'?<motion.section key="loading" className="loading-state" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} aria-live="polite" aria-busy="true"><span className="loading-dot"/><h2>Reading your collection</h2><p>Fetching item details from Steam. Large inventories may take a little longer.</p><button className="text-button" onClick={()=>{request.current?.abort();setStatus(data?'done':'idle');}}>Cancel</button></motion.section>:data&&<motion.section key="inventory" ref={inventory} className="inventory" initial={{opacity:0,y:reduced?0:18}} animate={{opacity:1,y:0}} transition={{duration:.3}} aria-label="Inventory">
 <div className="inventory-heading"><div><div className="collection-label">{data.steamId==='sample'?'SAMPLE COLLECTION':'PUBLIC INVENTORY'}</div><h2>The collection</h2><p>{data.steamId==='sample'?'Illustrative items. Export is available for testing.':`SteamID64 ${data.steamId}`}</p></div><div className="export-actions">{filtered.length!==data.items.length&&<button className="secondary" onClick={()=>exportRows(filtered)} disabled={!filtered.length}>Export filtered ({filtered.length})</button>}<button className="primary" onClick={()=>exportRows(data.items)} disabled={!data.items.length}>{exported?<Check size={18}/>:<DownloadSimple size={18}/>} {exported?'Download started':'Export CSV'}<span>{data.items.length}</span></button><span role="status" className="sr-only">{exported?'CSV download started':''}</span></div></div>
 <div className="collection-summary"><span><b>{fmt(stats.total)}</b> items</span><span><b>{fmt(stats.unique)}</b> unique finishes</span><span><b>{fmt(stats.tradable)}</b> tradable now</span><span className="summary-note"><ShieldCheck size={17}/>Public data. Read only.</span></div>
 <div className="filters"><label className="search"><MagnifyingGlass size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a skin or collection" aria-label="Search items"/></label><select aria-label="Rarity" value={rarity} onChange={e=>setRarity(e.target.value)}><option value="">All rarities</option>{stats.rarities.map(r=><option key={r}>{r}</option>)}</select><select aria-label="Sort items" value={sort} onChange={e=>setSort(e.target.value)}><option value="inventory">Inventory order</option><option value="rarity">Rarity first</option><option value="name">Name A–Z</option></select><div className="view-switch" role="group" aria-label="Inventory view"><button aria-label="Grid view" aria-pressed={view==='grid'} onClick={()=>setView('grid')}><SquaresFour size={20}/></button><button aria-label="List view" aria-pressed={view==='list'} onClick={()=>setView('list')}><List size={20}/></button></div></div>
 <div className="filter-options"><label><input type="checkbox" checked={grouped} onChange={e=>setGrouped(e.target.checked)}/>Group duplicates</label><label><input type="checkbox" checked={tradable} onChange={e=>setTradable(e.target.checked)}/>Tradable only</label>{(query||rarity||tradable)&&<button className="clear-filters" onClick={()=>{setQuery('');setRarity('');setTradable(false);}}>Clear filters<X size={13}/></button>}<span>{shown.length} rows shown{shown.length>120?' · First 120 previewed':''}</span></div>
 {shown.length?<div className={view==='grid'?'item-grid':'item-list'}>{shown.slice(0,120).map(i=><motion.button layout="position" transition={{duration:.2}} key={i.assetId} className="inventory-item" onClick={()=>setSelected(i)} whileTap={reduced?{}:{scale:.985}} style={{'--rarity':i.rarityColor||'#737373'}}><div className="item-art">{i.iconUrl&&<img src={i.iconUrl} alt="" loading="lazy"/>}{i.amount>1&&<span className="quantity">×{i.amount}</span>}</div><div className="item-copy"><span className="item-type">{i.weapon||i.type}</span><h3>{view==='grid'?i.name.replace(/^.*? \| /,'').replace(/ \([^)]*\)$/ ,''):i.name}</h3><p>{i.exterior||i.rarity||'Item'}</p><div className="item-status"><span className="rarity-name">{i.rarity}</span><span>{i.tradable?'Tradable':i.tradeHold?'Trade hold':'Not tradable'}</span></div></div><ArrowUpRight className="inspect-arrow" size={18}/></motion.button>)}</div>:<div className="empty-state"><h3>{data.items.length?'No matching items':'This inventory is empty'}</h3><p>{data.items.length?'Try another search or clear your filters.':'There are no CS2 items in this public inventory.'}</p>{data.items.length>0&&<button className="secondary" onClick={()=>{setQuery('');setRarity('');setTradable(false);}}>Clear filters</button>}</div>}
 <p className="export-note">CSV exports include every selected asset, with one row per asset. Grouping only changes this preview.</p>
 </motion.section>}</AnimatePresence>
 <section className="workflow" id="how"><div><h2>From loadout<br/>to spreadsheet.</h2><p>No trading. No account access.<br/>Just a better view of what you own.</p></div><ol><li><span>01</span><div><h3>Connect a public profile</h3><p>Paste a Steam link or ID. Only public CS2 inventory data is requested.</p></div></li><li><span>02</span><div><h3>Make sense of your collection</h3><p>Find finishes, compare rarity, and separate items that are ready to trade.</p></div></li><li><span>03</span><div><h3>Take it anywhere</h3><p>Download a spreadsheet-ready CSV for Excel or Google Sheets.</p></div></li></ol></section>
 </main><footer><span>CS2 Inventory Exporter</span><span>Not affiliated with Valve or Steam.</span><a href="#how">How it works <ArrowUpRight size={14}/></a></footer>
 <dialog ref={dialog} aria-labelledby="item-detail-title" className="item-dialog" onCancel={()=>setSelected(null)} onClose={()=>setSelected(null)} onClick={e=>{if(e.target===e.currentTarget){dialog.current.close();setSelected(null);}}}>{selected&&<><button className="dialog-close secondary" aria-label="Close item details" onClick={()=>{dialog.current.close();setSelected(null);}}><X size={20}/></button><div className="dialog-art"><img src={selected.iconUrl} alt={selected.name}/></div><div className="dialog-copy"><p>{selected.rarity} · {selected.exterior||selected.type}</p><h2 id="item-detail-title">{selected.name}</h2><dl><div><dt>Collection</dt><dd>{selected.collection||'Not specified'}</dd></div><div><dt>Trade status</dt><dd>{selected.tradable?'Tradable':selected.tradeHold||'Not tradable'}</dd></div><div><dt>Quantity</dt><dd>{selected.amount}</dd></div></dl>{selected.marketUrl&&<a className="primary" href={selected.marketUrl} target="_blank" rel="noreferrer">View on Steam Market<ArrowUpRight size={18}/></a>}</div></>}</dialog>
 </div></MotionConfig>;
}
